### PR TITLE
Make 2.5.1 stable

### PR DESCRIPTION
**Pull request by AnakinSklavenwalker**
I https://github.com/CodeShield-Security/SPDS/ is the new main repo, i think it make sense to have one last stable release for this repo. 

Changes:
- Bump all pending version updates
- Use new Soot repo
- disabled Test WPDSPostStarTests::push1 which is also disabled in the Codeshields repo
- fixed old bug on mine

### CODE REVIEW

**Comment by johspaeth** [comment]
Thanks a lot. Unfortunately, the pipeline is still failing. I will merge once the pipeline doesn't.

**Comment by AnakinSklavenwalker** [comment]
yeah there are still some tests failing, but i don't know how to fix them

**Comment by johspaeth** [comment]
Ok.

* disabled Test WPDSPostStarTests::push1 which is also disabled in the Codeshields repo

seems to be the issue. 

I'll have a look at it. Thanks for preparing the draft.

**Comment by AnakinSklavenwalker** [comment]
thanks!

**Comment by AnakinSklavenwalker** [comment]
so adding the changed file eventually makes the CI pass. Not sure though if the disabled test should be fixed and activated.

**Review by johspaeth — APPROVED** [review]

**Pull request merged**
